name: rally_fotografico
description: "A new Flutter project."
publish_to: 'none'
version: 1.4.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  image_picker: ^0.8.6
  firebase_storage: ^12.4.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "G:\\Mi unidad\\PI\\IMG APK\\Logo2.png"
