// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQW9DFtW7l2EEffwKYMVFkeRQ-Q1FSdko',
    appId: '1:112658903542:web:93d13fb4600c6c15b8d7d7',
    messagingSenderId: '112658903542',
    projectId: 'rallyfotografico-c02ce',
    authDomain: 'rallyfotografico-c02ce.firebaseapp.com',
    storageBucket: 'rallyfotografico-c02ce.firebasestorage.app',
    measurementId: 'G-0ZJQH9K4DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArROHJlDysycP2HUNezNsNITzxC6XgB6k',
    appId: '1:112658903542:android:66d58f2f2ca56804b8d7d7',
    messagingSenderId: '112658903542',
    projectId: 'rallyfotografico-c02ce',
    storageBucket: 'rallyfotografico-c02ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1--q1kcyxNNByuJdeI9DMGIW3FoUJTWE',
    appId: '1:112658903542:ios:d078044bc8b61e94b8d7d7',
    messagingSenderId: '112658903542',
    projectId: 'rallyfotografico-c02ce',
    storageBucket: 'rallyfotografico-c02ce.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1--q1kcyxNNByuJdeI9DMGIW3FoUJTWE',
    appId: '1:112658903542:ios:d078044bc8b61e94b8d7d7',
    messagingSenderId: '112658903542',
    projectId: 'rallyfotografico-c02ce',
    storageBucket: 'rallyfotografico-c02ce.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQW9DFtW7l2EEffwKYMVFkeRQ-Q1FSdko',
    appId: '1:112658903542:web:1c0d0b8001fa37b9b8d7d7',
    messagingSenderId: '112658903542',
    projectId: 'rallyfotografico-c02ce',
    authDomain: 'rallyfotografico-c02ce.firebaseapp.com',
    storageBucket: 'rallyfotografico-c02ce.firebasestorage.app',
    measurementId: 'G-VFMPHHSCSH',
  );
}
